# These are supported funding model platforms

github: # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [joker, Mary]
patreon: # Replace with a single Patreon username voodoo.io
open_collective: # Replace with a single Open Collective username Tornado.io
ko_fi: # Replace with a single Ko-fi username atom
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
community_bridge: # Replace with a single Community Bridge project-name e.g., cloud-foundry
liberapay: # Replace with a single Liberapay username Greg
issuehunt: # Replace with a single IssueHunt username Kelli
otechie: # Replace with a single Otechie username justin
custom: # Replace with up to 4 custom sponsorship URLs e.g., ['https://Marlboro.com', 'https://dollarshaveclub.com' 'https://citytelecoin.com' ,'Https://Ibotta.com' , https://beachbodyondemand.com" https://pampers.com']
